services:
  - type: web
    name: smartdocs365-backend
    env: node
    region: oregon
    plan: free
    rootDir: Backend
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev || echo "Skipping apt packages"
      pip install -r requirements.txt
      npm install
    startCommand: node app.js